// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526182458_AddPrimeiroAcessoToken")]
    partial class AddPrimeiroAcessoToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Academico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioSaida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrecisaDefinirSenha")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimeiroAcessoToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PrimeiroAcessoTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Academicos");
                });

            modelBuilder.Entity("backend.Models.RegistroPonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("TotalTrabalhado")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("AcademicoId");

                    b.ToTable("RegistrosPonto");
                });

            modelBuilder.Entity("backend.Models.RegistroPonto", b =>
                {
                    b.HasOne("backend.Models.Academico", "Academico")
                        .WithMany()
                        .HasForeignKey("AcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academico");
                });
#pragma warning restore 612, 618
        }
    }
}
